### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by roj1512** [comment]
Damn

**Comment by oxalorg** [comment]
@roj1512 Thanks for your contribution. Apologies I thought this was done by a bot. If you're interested in contributing to Sakura.css, would appreciate if you can make look at one of the issues and contribute to those instead.

Thanks! 🌸

**Comment by roj1512** [comment]
Cool! Although, I wouldn't contribute to anything which has GitHub as Github or things like JavaScript as Javascript in their READMEs.

**Comment by oxalorg** [comment]
Fair enough, apologies from my end. 🙏

**Comment by oxalorg** [comment]
Your fix is in, maybe you can take a look at issues now haha? :)

**Pull request merged**
